version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5555:5432'
    environment:
      POSTGRES_PASSWORD: pass123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
